configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/sra.smk"
include: "rules/map.smk"
include: "rules/signal.smk"
include: "rules/epest.smk"

wildcard_constraints:
    sample="|".join(list(samples["sample"])),

rule all:
    input:
        outputs
