# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

#include: "rules/common.smk"
include: "rules/sra.smk"

#rule all:
#    input:
#        get_output
