configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/sra.smk"
include: "rules/map.smk"
include: "rules/signal.smk"
include: "rules/epest.smk"

rule all:
    input:
        outputs
